### ISSUE TITLE
ROIs missing from captured image on mac

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#1]
Submitter: Collin
Email: collin.poczatek@gmail.com
ROIs don't appear when calling "Capture Image" on a Mac.

[Also this bug submitted through git reports as a first test]

**Comment by taylorwrt** [comment]
The ability to save ROIs was of course already present in the code, in the drawOverlay method of MimsCanvas.java, so by copying some of that logic and putting it in captureImageMenuItemActionPerformed method of UI.java, I was able to get ROIs to be including on captured images.

**Comment by taylorwrt** [comment]
This bug was not completely fixed:  This worked fine on MacOS, but on Linux, the number label for each ROI was present twice.  This has now been fixed, though it should be noted that on MacOS, the labels on the captured image are in the center of the ROIs, while on Linux they are in the upper right corner of the ROI, as they appear on screen.
