### ISSUE TITLE
Add git commit to "about openmims"

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#23]
The build used to put the svn revision number into the OpenMIMS jar. Since we moved to git this has just been commented out. Should use git commit #.

**Comment by cpoczatek** [comment]
Reopening because we should figure out tags in a smarter way.

[embed git build num](http://stackoverflow.com/questions/6458883/how-can-i-get-the-git-build-number-and-embed-it-in-a-file)

```
git describe 

....

--long
Always output the long format (the tag, the number of commits and the abbreviated commit name) 
even when it matches a tag. This is useful when you want to see parts of the commit object name in 
"describe" output, even when the commit in question happens to be a tagged version. Instead of just 
emitting the tag name, it will describe such a commit as v1.2-0-gdeadbee (0th commit since tag v1.2 
that points at object deadbee…​.).
```

**Comment by taylorwrt** [comment]
In order to get the ball rolling on taggin of OpenMIMS revisions, I tagged the current state of the project like this:
git tag -a v3.0.4 -m "OpenMIMS version 3.0.4"

In the future, only do this upon version updates.  After tagging, run this:
git describe --all --long > version.txt

This version.txt file will then be committed to Github.
