### ISSUE TITLE
installation/update error

### ISSUE THREAD

**Issue by 1cuigx** [BWHCNI/OpenMIMS#58]
It seems that the package has been moved to a new site, however, the installation/update site in Fiji still directs to http://nrims.partners.org/OpenMIMS-Fiji/. Can you please provide an updated link, so I can add it to Fiji and get the package installed. Thank you.

**Comment by taylorwrt** [comment]
Guoxin,

In order to use the most recent OpenMIMS, you should follow this procedure:

1.  Download a fresh copy of Fiji from https://imagej.net/Fiji/Downloads <https://imagej.net/Fiji/Downloads> and run it.  If you are using a Mac, when you try to run it, you may see a security dialog that says "Fiji.app is an application downloaded from the internet.  Are you sure you want to open it?   If so, click on Open.

2.  In Fiji, go to the Help menu and select "Update ..."   Let it download all the updates.  Do not close the ImageJ Updater window yet.
3.  Still in the ImageJ Updater window, select the "Manage update sites" button on the lower left.  In the ensuing window, scroll down to the OpenMIMS entry, and check the checkbox on the left.  The URL there should be "http://sites.imagej.net/OpenMIMS2/ <http://sites.imagej.net/OpenMIMS2/>        If not, let me know.
4.  You should see a long list of new jar files to be installed.  Click on the "Apple changes" button to install them.  It will install them and then tell you to restart ImageJ (Fiji), so do that.
4.  One Fiji has been restarted, you should see the new entry "Open MIMS Image" under the Plugins menu.  You can select that to run OpenMIMS.

If any of this does not work, email me at walter.taylor@icloud.com <mailto:walter.taylor@icloud.com>




Walter Taylor
IS Programmer/Analyst
Center for NanoImaging
Brigham and Women's Hospital
65 Landsdowne St
Cambridge, MA  02139

617-803-5874

wrtaylor@partners.org
walter.taylor@icloud.com

https://nano.bwh.harvard.edu/

**Comment by 1cuigx** [comment]
Walter,

Thank you very much for the quick response. It works (Oh Yeah)! 

I tried to update Fiji from the app side, I thought it was already the latest version, turns out it is not the case.

Thanks,
Guoxin
